export const SIGN_OUT = "SIGN_OUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const SET_USER = "SET_USER";
export const SIGNING_IN = "SIGNING_IN";

export const CREATING_COUPON = "CREATING_COUPON";
export const CREATE_COUPON_FAILD = "CREATE_COUPON_FAILD";
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";

export const CHECKING_COUPON = "CHECKING_COUPON";
export const CHECK_COUPON_FAILED = "CHECK_COUPON_FAILED";
export const CHECK_COUPON_SUCCESS = "CHECK_COUPON_SUCCESS";
